# Generated by Django 4.2.2 on 2023-06-26 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/content/')),
                ('views', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('coffeeChatRequests', models.IntegerField(default=0)),
                ('category', models.CharField(blank=True, choices=[('Life Space', 'Life Space'), ('Work Space', 'Work Space'), ('Study Space', 'Study Space'), ('Team Space', 'Team Space')], max_length=60, null=True)),
                ('isTodayPick', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
